In [1]:
import pandas as pd
from decimal import Decimal

In [2]:
# Read csv
heart_df = pd.read_csv("../Resources/Heart Disease Mortality by State data-table.csv")
insurance_df = pd.read_csv("../Resources/Health Insurance Coverage of the Total Population raw_data.csv")
expenditures_df = pd.read_csv("../Resources/Health Care Expenditures per Capita by State of Residence raw_data.csv")

# heart_df

In [3]:
# Drop unnecessary columns
heart_df = heart_df.drop(columns="URL")
heart_df.head()

   YEAR STATE   RATE DEATHS
0  2020    AL  237.5  14739
1  2020    AK  139.8    915
2  2020    AZ  144.8  14196
3  2020    AR  222.5   8621
4  2020    CA  144.0  66538

In [4]:
# Rename columns
heart_df = heart_df.rename(columns = {"YEAR":"Year","STATE":"State","RATE":"Rate (per 100,000)","DEATHS":"Deaths"})
heart_df.head()

   Year State  Rate (per 100,000) Deaths
0  2020    AL               237.5  14739
1  2020    AK               139.8    915
2  2020    AZ               144.8  14196
3  2020    AR               222.5   8621
4  2020    CA               144.0  66538

In [5]:
# Filter for year 2019
year = [2019]

for year in year:
    heart_df = heart_df.loc[heart_df["Year"] == year, :]
heart_df.head()

    Year State  Rate (per 100,000) Deaths
50  2019    AL               219.6  13448
51  2019    AK               129.7    843
52  2019    AZ               134.0  12587
53  2019    AR               226.5   8669
54  2019    CA               136.9  62394

In [6]:
# Reset index
heart_df = heart_df.reset_index(drop = True)
heart_df.head()

   Year State  Rate (per 100,000) Deaths
0  2019    AL               219.6  13448
1  2019    AK               129.7    843
2  2019    AZ               134.0  12587
3  2019    AR               226.5   8669
4  2019    CA               136.9  62394

In [7]:
# Creating a Dictionary of States Abbreviation to State name
states_long = {
    "AL" : "Alabama",
    "AK" : "Alaska",
    "AZ" : "Arizona",
    "AR" : "Arkansas",
    "CA" : "California",
    "CO" : "Colorado",
    "CT" : "Connecticut",
    "DE" : "Delaware",
    "FL" : "Florida" ,
    "GA" : "Georgia",
    "HI" : "Hawaii",
    "ID" : "Idaho",
    "IL" : "Illinois",
    "IN" : "Indiana",
    "IA" : "Iowa",
    "KS" : "Kansas",
    "KY" : "Kentucky",
    "LA" : "Louisiana",
    "ME" : "Maine",
    "MD" : "Maryland",
    "MA" : "Massachusetts",
    "MI" : "Michigan",
    "MN" : "Minnesota",
    "MS" : "Mississippi",
    "MO" : "Missouri",
    "MT" : "Montana",
    "NE" : "Nebraska",
    "NV" : "Nevada",
    "NH" : "New Hampshire",
    "NJ" : "New Jersey",
    "NM" : "New Mexico",
    "NY" : "New York",
    "NC" : "North Carolina",
    "ND" : "North Dakota",
    "OH" : "Ohio",
    "OK" : "Oklahoma",
    "OR" : "Oregon",
    "PA" : "Pennsylvania",
    "RI" : "Rhode Island",
    "SC" : "South Carolina",
    "SD" : "South Dakota",
    "TN" : "Tennessee",
    "TX" : "Texas",
    "UT" : "Utah",
    "VT" : "Vermont",
    "VA" : "Virginia",
    "WA" : "Washington",
    "WV" : "West Virginia",
    "WI" : "Wisconsin",
    "WY" : "Wyoming",
    "DC" : "District of Columbia",
    "AS" : "American Samoa",
    "GU" : "Guam",
    "MP" : "Northern Mariana Islands",
    "PR" : "Puerto Rico",
    "UM" : "United States Minor Outlying Islands",
    "VI" : "U.S. Virgin Islands",
}

# Using .replace to replace State Abbreviation with State Name from the dictionary
heart_df['State'] = heart_df['State'].replace(states_long)

heart_df

    Year           State  Rate (per 100,000) Deaths
0   2019         Alabama               219.6  13448
1   2019          Alaska               129.7    843
2   2019         Arizona               134.0  12587
3   2019        Arkansas               226.5   8669
4   2019      California               136.9  62394
5   2019        Colorado               127.7   7762
6   2019     Connecticut               143.1   7354
7   2019        Delaware               154.3   2053
8   2019         Florida               140.1  47144
9   2019         Georgia               175.5  19543
10  2019          Hawaii               120.3   2503
11  2019           Idaho               150.7   3061
12  2019        Illinois               162.0  25690
13  2019         Indiana               178.8  14555
14  2019            Iowa               172.9   7505
15  2019          Kansas               166.0   6140
16  2019        Kentucky               196.4  10742
17  2019       Louisiana               207.8  11302
18  2019           Maine               142.4   2940
19  2019        Maryland               159.3  11770
20  2019   Massachusetts               127.2  11761
21  2019        Michigan               193.8  25547
22  2019       Minnesota               116.7   8401
23  2019     Mississippi               226.7   7997
24  2019        Missouri               187.0  15018
25  2019         Montana               157.1   2290
26  2019        Nebraska               144.9   3540
27  2019          Nevada               198.1   6864
28  2019   New Hampshire               143.4   2707
29  2019      New Jersey               158.0  18716
30  2019      New Mexico               158.2   4245
31  2019        New York               166.6  43806
32  2019  North Carolina               154.7  19617
33  2019    North Dakota               147.7   1448
34  2019            Ohio               188.8  29160
35  2019        Oklahoma               231.4  10960
36  2019          Oregon               131.0   7128
37  2019    Pennsylvania               172.9  32299
38  2019    Rhode Island               159.3   2404
39  2019  South Carolina               164.0  10579
40  2019    South Dakota               158.1   1840
41  2019       Tennessee               202.8  16814
42  2019           Texas               163.4  46139
43  2019            Utah               146.5   3882
44  2019         Vermont               151.6   1368
45  2019        Virginia               149.1  15062
46  2019      Washington               134.8  11862
47  2019   West Virginia               197.4   5087
48  2019       Wisconsin               158.8  12241
49  2019         Wyoming               150.4   1067

# insurance_df

In [8]:
# Drop unnecessary rows
insurance_df = insurance_df.iloc[:54]
insurance_df.head()

,Title: Health Insurance Coverage of the Total Population | KFF,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,Timeframe: 2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Location,Employer,Non-Group,Medicaid,Medicare,Military,Uninsured,Total,Footnotes
2,United States,0.496,0.059,0.198,0.142,0.014,0.092,1,1
3,Alabama,0.472,0.055,0.195,0.16,0.021,0.097,1,NaN
4,Alaska,0.484,0.035,0.213,0.1,0.053,0.115,1,NaN

In [9]:
# Drop more unnecessary rows and reset index
insurance_df = insurance_df.drop(labels=[0,1,2,11])
insurance_df = insurance_df.reset_index(drop=True)
insurance_df.head()

,Title: Health Insurance Coverage of the Total Population | KFF,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,Alabama,0.472,0.055,0.195,0.16,0.021,0.097,1,NaN
1,Alaska,0.484,0.035,0.213,0.1,0.053,0.115,1,NaN
2,Arizona,0.451,0.052,0.21,0.161,0.015,0.111,1,NaN
3,Arkansas,0.42,0.054,0.262,0.159,0.014,0.091,1,NaN
4,California,0.48,0.066,0.253,0.114,0.009,0.078,1,NaN

In [10]:
#Rename columns to be used later
insurance_df = insurance_df.rename(columns={"Title: Health Insurance Coverage of the Total Population | KFF":"State",
                                            "Unnamed: 1":"Employer (%)",
                                            "Unnamed: 2":"Non-Group (%)",
                                            "Unnamed: 3":"Medicaid (%)",
                                            "Unnamed: 4":"Medicare (%)",
                                            "Unnamed: 5":"Military (%)",
                                            "Unnamed: 6":"Uninsured (%)"})
insurance_df.head()

,State,Employer (%),Non-Group (%),Medicaid (%),Medicare (%),Military (%),Uninsured (%),Unnamed: 7,Unnamed: 8
0,Alabama,0.472,0.055,0.195,0.16,0.021,0.097,1,NaN
1,Alaska,0.484,0.035,0.213,0.1,0.053,0.115,1,NaN
2,Arizona,0.451,0.052,0.21,0.161,0.015,0.111,1,NaN
3,Arkansas,0.42,0.054,0.262,0.159,0.014,0.091,1,NaN
4,California,0.48,0.066,0.253,0.114,0.009,0.078,1,NaN

In [11]:
# Create lists
states = []
employer = []
nongrp = []
medicaid = []
medicare = []
military = []
uninsured = []
insured = []


for index, row in insurance_df.iterrows():
    state = insurance_df.loc[index, "State"]
    uninsured_dec = insurance_df.loc[index, "Uninsured (%)"]
    employer_dec = insurance_df.loc[index, "Employer (%)"]
    nongrp_dec = insurance_df.loc[index, "Non-Group (%)"]
    medicaid_dec = insurance_df.loc[index, "Medicaid (%)"]
    medicare_dec = insurance_df.loc[index, "Medicare (%)"]
    military_dec = insurance_df.loc[index, "Military (%)"]
    uninsured_per = (Decimal(uninsured_dec) * Decimal(100))
    employer_per = (Decimal(employer_dec)*Decimal(100))
    nongrp_per = (Decimal(nongrp_dec)*Decimal(100))
    medicaid_per = (Decimal(medicaid_dec)*Decimal(100))
    medicare_per = (Decimal(medicare_dec)*Decimal(100))
    military_per = (Decimal(military_dec)*Decimal(100))
    percent = (Decimal(100) - Decimal(uninsured_per))
    states.append(state)
    employer.append(float(employer_per))
    nongrp.append(float(nongrp_per))
    medicaid.append(float(medicaid_per))
    medicare.append(float(medicare_per))
    military.append(float(military_per))
    uninsured.append(float(uninsured_per))
    insured.append(float(percent))

In [12]:
# Create new dataframe
insurance_df = pd.DataFrame({
    "State": states,
    "Employer (%)": employer,
    "Non-Group (%)": nongrp,
    "Medicaid (%)": medicaid,
    "Medicare (%)": medicare,
    "Military (%)": military,
    "Total Insured (%)": insured,
    "Uninsured (%)": uninsured,
})
insurance_df

,State,Employer (%),Non-Group (%),Medicaid (%),Medicare (%),Military (%),Total Insured (%),Uninsured (%)
0,Alabama,47.2,5.5,19.5,16.0,2.1,90.3,9.7
1,Alaska,48.4,3.5,21.3,10.0,5.3,88.5,11.5
2,Arizona,45.1,5.2,21.0,16.1,1.5,88.9,11.1
3,Arkansas,42.0,5.4,26.2,15.9,1.4,90.9,9.1
4,California,48.0,6.6,25.3,11.4,0.9,92.2,7.8
5,Colorado,53.4,6.9,16.8,12.8,2.3,92.2,7.8
6,Connecticut,52.9,4.8,21.5,14.1,0.7,94.1,5.9
7,Delaware,49.7,4.1,20.4,17.3,1.8,93.4,6.6
8,Florida,40.3,9.5,17.4,18.0,1.7,86.9,13.1
9,Georgia,48.9,5.6,17.3,12.6,2.2,86.6,13.4
10,Hawaii,54.3,4.1,17.6,15.9,4.0,95.9,4.1
11,Idaho,49.0,8.6,15.6,15.0,1.4,89.5,10.5
12,Illinois,54.6,5.2,18.2,14.1,0.7,92.7,7.3
13,Indiana,53.3,4.4,17.7,14.8,1.0,91.2,8.8
14,Iowa,54.4,4.9,19.5,15.6,0.9,95.3,4.7
15,Kansas,54.3,5.6,13.9,15.0,2.0,90.8,9.2
16,Kentucky,47.0,3.9,25.5,15.8,1.4,93.6,6.4
17,Louisiana,41.8,4.9,29.3,13.7,1.4,91.1,8.9
18,Maine,46.5,5.7,20.0,18.3,1.5,91.9,8.1
19,Maryland,54.7,5.4,18.7,13.3,1.9,94.1,5.9
20,Massachusetts,55.9,5.4,22.1,13.1,0.5,97.0,3.0
21,Michigan,50.9,5.2,21.7,15.9,0.6,94.2,5.8
22,Minnesota,57.8,5.2,16.9,14.7,0.7,95.2,4.8
23,Mississippi,42.2,4.7,24.2,14.2,1.8,87.1,12.9
24,Missouri,52.0,5.7,14.4,16.4,1.3,89.9,10.1
25,Montana,43.0,8.0,20.8,18.1,1.8,91.7,8.3
26,Nebraska,56.8,6.9,12.6,14.2,1.6,92.1,7.9
27,Nevada,49.5,5.5,17.8,14.0,1.7,88.5,11.5
28,New Hampshire,56.2,5.3,13.2,17.7,1.2,93.6,6.4
29,New Jersey,55.7,5.4,16.6,13.8,0.5,92.1,7.9
30,New Mexico,36.6,4.0,32.7,15.0,1.8,90.2,9.8
31,New York,49.8,5.8,25.7,13.0,0.4,94.7,5.3
32,North Carolina,46.3,6.7,17.9,15.3,2.4,88.6,11.4
33,North Dakota,55.7,9.0,12.2,13.8,2.1,92.6,7.4
34,Ohio,52.6,4.0,20.0,15.9,0.8,93.3,6.7
35,Oklahoma,45.5,5.5,17.0,15.1,2.0,85.1,14.9
36,Oregon,49.3,5.7,20.8,16.2,0.9,92.9,7.1
37,Pennsylvania,51.8,5.1,20.2,16.3,0.8,94.3,5.7
38,Rhode Island,54.0,5.9,20.5,14.6,0.8,95.7,4.3
39,South Carolina,45.4,6.1,18.8,16.8,2.2,89.2,10.8
40,South Dakota,51.5,8.3,12.8,16.1,1.8,90.4,9.6
41,Tennessee,47.8,5.6,19.5,15.0,1.8,89.8,10.2
42,Texas,47.6,5.7,15.9,10.9,1.6,81.6,18.4
43,Utah,60.5,9.3,9.3,10.0,1.2,90.4,9.6
44,Vermont,48.4,4.8,23.9,17.5,1.0,95.6,4.4
45,Virginia,54.1,5.2,13.5,14.8,4.4,92.0,8.0
46,Washington,52.9,5.0,19.8,13.9,1.8,93.4,6.6
47,West Virginia,44.0,2.5,26.6,19.0,1.3,93.4,6.6
48,Wisconsin,56.5,5.3,16.1,15.5,0.8,94.2,5.8
49,Wyoming,51.1,7.1,11.5,16.2,1.8,87.7,12.3

# expenditures_df

In [13]:
# Rename Columns
expenditures_df = expenditures_df.rename(columns={"Title: Health Care Expenditures per Capita by State of Residence | KFF"\
                                                 :"State","Unnamed: 1":"Health Spending per Capita"})
expenditures_df

,State,Health Spending per Capita
0,Timeframe: 2019,NaN
1,Location,Health Spending per Capita
2,United States,"$9,671"
3,Alabama,"$8,741"
4,Alaska,"$13,226"
...,...,...
62,Sources,NaN
63,"Centers for Medicare & Medicaid Services, Offi...",NaN
64,NaN,NaN
65,Definitions,NaN
66,*Health Spending Per Capita* includes spending...,NaN

In [14]:
# Drop unnecessary rows
expenditures_df = expenditures_df.drop(labels=[0,1,2,11])
expenditures_df = expenditures_df.iloc[:50]

In [15]:
# Reset index
expenditures_df = expenditures_df.reset_index(drop=True)
expenditures_df

             State Health Spending per Capita
0          Alabama                    $8,741
1           Alaska                   $13,226
2          Arizona                    $8,145
3         Arkansas                    $8,853
4       California                    $9,628
5         Colorado                    $8,286
6      Connecticut                   $11,831
7         Delaware                   $12,213
8          Florida                    $9,490
9          Georgia                    $8,243
10          Hawaii                    $9,555
11           Idaho                    $7,723
12        Illinois                    $9,496
13         Indiana                    $9,927
14            Iowa                    $9,193
15          Kansas                    $8,745
16        Kentucky                    $9,744
17       Louisiana                    $9,657
18           Maine                   $11,488
19        Maryland                   $10,248
20   Massachusetts                   $12,729
21        Michigan                    $9,532
22       Minnesota                   $10,510
23     Mississippi                    $8,745
24        Missouri                    $9,431
25         Montana                    $9,808
26        Nebraska                    $9,917
27          Nevada                    $8,114
28   New Hampshire                   $11,310
29      New Jersey                   $11,264
30      New Mexico                    $8,459
31        New York                   $12,932
32  North Carolina                    $8,619
33    North Dakota                   $10,653
34            Ohio                   $10,173
35        Oklahoma                    $8,923
36          Oregon                    $9,635
37    Pennsylvania                   $11,175
38    Rhode Island                   $10,988
39  South Carolina                    $8,345
40    South Dakota                   $11,627
41       Tennessee                    $8,827
42           Texas                    $8,028
43            Utah                    $7,193
44         Vermont                   $12,159
45        Virginia                    $8,826
46      Washington                    $8,964
47   West Virginia                   $11,951
48       Wisconsin                    $9,652
49         Wyoming                   $10,111

# Merged DataFrame

In [16]:
merged_df_1 = pd.merge(heart_df, insurance_df, how="outer", on="State")
merged_df_1

,Year,State,"Rate (per 100,000)",Deaths,Employer (%),Non-Group (%),Medicaid (%),Medicare (%),Military (%),Total Insured (%),Uninsured (%)
0,2019,Alabama,219.6,13448,47.2,5.5,19.5,16.0,2.1,90.3,9.7
1,2019,Alaska,129.7,843,48.4,3.5,21.3,10.0,5.3,88.5,11.5
2,2019,Arizona,134.0,12587,45.1,5.2,21.0,16.1,1.5,88.9,11.1
3,2019,Arkansas,226.5,8669,42.0,5.4,26.2,15.9,1.4,90.9,9.1
4,2019,California,136.9,62394,48.0,6.6,25.3,11.4,0.9,92.2,7.8
5,2019,Colorado,127.7,7762,53.4,6.9,16.8,12.8,2.3,92.2,7.8
6,2019,Connecticut,143.1,7354,52.9,4.8,21.5,14.1,0.7,94.1,5.9
7,2019,Delaware,154.3,2053,49.7,4.1,20.4,17.3,1.8,93.4,6.6
8,2019,Florida,140.1,47144,40.3,9.5,17.4,18.0,1.7,86.9,13.1
9,2019,Georgia,175.5,19543,48.9,5.6,17.3,12.6,2.2,86.6,13.4
10,2019,Hawaii,120.3,2503,54.3,4.1,17.6,15.9,4.0,95.9,4.1
11,2019,Idaho,150.7,3061,49.0,8.6,15.6,15.0,1.4,89.5,10.5
12,2019,Illinois,162.0,25690,54.6,5.2,18.2,14.1,0.7,92.7,7.3
13,2019,Indiana,178.8,14555,53.3,4.4,17.7,14.8,1.0,91.2,8.8
14,2019,Iowa,172.9,7505,54.4,4.9,19.5,15.6,0.9,95.3,4.7
15,2019,Kansas,166.0,6140,54.3,5.6,13.9,15.0,2.0,90.8,9.2
16,2019,Kentucky,196.4,10742,47.0,3.9,25.5,15.8,1.4,93.6,6.4
17,2019,Louisiana,207.8,11302,41.8,4.9,29.3,13.7,1.4,91.1,8.9
18,2019,Maine,142.4,2940,46.5,5.7,20.0,18.3,1.5,91.9,8.1
19,2019,Maryland,159.3,11770,54.7,5.4,18.7,13.3,1.9,94.1,5.9
20,2019,Massachusetts,127.2,11761,55.9,5.4,22.1,13.1,0.5,97.0,3.0
21,2019,Michigan,193.8,25547,50.9,5.2,21.7,15.9,0.6,94.2,5.8
22,2019,Minnesota,116.7,8401,57.8,5.2,16.9,14.7,0.7,95.2,4.8
23,2019,Mississippi,226.7,7997,42.2,4.7,24.2,14.2,1.8,87.1,12.9
24,2019,Missouri,187.0,15018,52.0,5.7,14.4,16.4,1.3,89.9,10.1
25,2019,Montana,157.1,2290,43.0,8.0,20.8,18.1,1.8,91.7,8.3
26,2019,Nebraska,144.9,3540,56.8,6.9,12.6,14.2,1.6,92.1,7.9
27,2019,Nevada,198.1,6864,49.5,5.5,17.8,14.0,1.7,88.5,11.5
28,2019,New Hampshire,143.4,2707,56.2,5.3,13.2,17.7,1.2,93.6,6.4
29,2019,New Jersey,158.0,18716,55.7,5.4,16.6,13.8,0.5,92.1,7.9
30,2019,New Mexico,158.2,4245,36.6,4.0,32.7,15.0,1.8,90.2,9.8
31,2019,New York,166.6,43806,49.8,5.8,25.7,13.0,0.4,94.7,5.3
32,2019,North Carolina,154.7,19617,46.3,6.7,17.9,15.3,2.4,88.6,11.4
33,2019,North Dakota,147.7,1448,55.7,9.0,12.2,13.8,2.1,92.6,7.4
34,2019,Ohio,188.8,29160,52.6,4.0,20.0,15.9,0.8,93.3,6.7
35,2019,Oklahoma,231.4,10960,45.5,5.5,17.0,15.1,2.0,85.1,14.9
36,2019,Oregon,131.0,7128,49.3,5.7,20.8,16.2,0.9,92.9,7.1
37,2019,Pennsylvania,172.9,32299,51.8,5.1,20.2,16.3,0.8,94.3,5.7
38,2019,Rhode Island,159.3,2404,54.0,5.9,20.5,14.6,0.8,95.7,4.3
39,2019,South Carolina,164.0,10579,45.4,6.1,18.8,16.8,2.2,89.2,10.8
40,2019,South Dakota,158.1,1840,51.5,8.3,12.8,16.1,1.8,90.4,9.6
41,2019,Tennessee,202.8,16814,47.8,5.6,19.5,15.0,1.8,89.8,10.2
42,2019,Texas,163.4,46139,47.6,5.7,15.9,10.9,1.6,81.6,18.4
43,2019,Utah,146.5,3882,60.5,9.3,9.3,10.0,1.2,90.4,9.6
44,2019,Vermont,151.6,1368,48.4,4.8,23.9,17.5,1.0,95.6,4.4
45,2019,Virginia,149.1,15062,54.1,5.2,13.5,14.8,4.4,92.0,8.0
46,2019,Washington,134.8,11862,52.9,5.0,19.8,13.9,1.8,93.4,6.6
47,2019,West Virginia,197.4,5087,44.0,2.5,26.6,19.0,1.3,93.4,6.6
48,2019,Wisconsin,158.8,12241,56.5,5.3,16.1,15.5,0.8,94.2,5.8
49,2019,Wyoming,150.4,1067,51.1,7.1,11.5,16.2,1.8,87.7,12.3

In [17]:
merged_df = pd.merge(merged_df_1, expenditures_df, how="outer", on=["State","State"])
merged_df

,Year,State,"Rate (per 100,000)",Deaths,Employer (%),Non-Group (%),Medicaid (%),Medicare (%),Military (%),Total Insured (%),Uninsured (%),Health Spending per Capita
0,2019,Alabama,219.6,13448,47.2,5.5,19.5,16.0,2.1,90.3,9.7,"$8,741"
1,2019,Alaska,129.7,843,48.4,3.5,21.3,10.0,5.3,88.5,11.5,"$13,226"
2,2019,Arizona,134.0,12587,45.1,5.2,21.0,16.1,1.5,88.9,11.1,"$8,145"
3,2019,Arkansas,226.5,8669,42.0,5.4,26.2,15.9,1.4,90.9,9.1,"$8,853"
4,2019,California,136.9,62394,48.0,6.6,25.3,11.4,0.9,92.2,7.8,"$9,628"
5,2019,Colorado,127.7,7762,53.4,6.9,16.8,12.8,2.3,92.2,7.8,"$8,286"
6,2019,Connecticut,143.1,7354,52.9,4.8,21.5,14.1,0.7,94.1,5.9,"$11,831"
7,2019,Delaware,154.3,2053,49.7,4.1,20.4,17.3,1.8,93.4,6.6,"$12,213"
8,2019,Florida,140.1,47144,40.3,9.5,17.4,18.0,1.7,86.9,13.1,"$9,490"
9,2019,Georgia,175.5,19543,48.9,5.6,17.3,12.6,2.2,86.6,13.4,"$8,243"
10,2019,Hawaii,120.3,2503,54.3,4.1,17.6,15.9,4.0,95.9,4.1,"$9,555"
11,2019,Idaho,150.7,3061,49.0,8.6,15.6,15.0,1.4,89.5,10.5,"$7,723"
12,2019,Illinois,162.0,25690,54.6,5.2,18.2,14.1,0.7,92.7,7.3,"$9,496"
13,2019,Indiana,178.8,14555,53.3,4.4,17.7,14.8,1.0,91.2,8.8,"$9,927"
14,2019,Iowa,172.9,7505,54.4,4.9,19.5,15.6,0.9,95.3,4.7,"$9,193"
15,2019,Kansas,166.0,6140,54.3,5.6,13.9,15.0,2.0,90.8,9.2,"$8,745"
16,2019,Kentucky,196.4,10742,47.0,3.9,25.5,15.8,1.4,93.6,6.4,"$9,744"
17,2019,Louisiana,207.8,11302,41.8,4.9,29.3,13.7,1.4,91.1,8.9,"$9,657"
18,2019,Maine,142.4,2940,46.5,5.7,20.0,18.3,1.5,91.9,8.1,"$11,488"
19,2019,Maryland,159.3,11770,54.7,5.4,18.7,13.3,1.9,94.1,5.9,"$10,248"
20,2019,Massachusetts,127.2,11761,55.9,5.4,22.1,13.1,0.5,97.0,3.0,"$12,729"
21,2019,Michigan,193.8,25547,50.9,5.2,21.7,15.9,0.6,94.2,5.8,"$9,532"
22,2019,Minnesota,116.7,8401,57.8,5.2,16.9,14.7,0.7,95.2,4.8,"$10,510"
23,2019,Mississippi,226.7,7997,42.2,4.7,24.2,14.2,1.8,87.1,12.9,"$8,745"
24,2019,Missouri,187.0,15018,52.0,5.7,14.4,16.4,1.3,89.9,10.1,"$9,431"
25,2019,Montana,157.1,2290,43.0,8.0,20.8,18.1,1.8,91.7,8.3,"$9,808"
26,2019,Nebraska,144.9,3540,56.8,6.9,12.6,14.2,1.6,92.1,7.9,"$9,917"
27,2019,Nevada,198.1,6864,49.5,5.5,17.8,14.0,1.7,88.5,11.5,"$8,114"
28,2019,New Hampshire,143.4,2707,56.2,5.3,13.2,17.7,1.2,93.6,6.4,"$11,310"
29,2019,New Jersey,158.0,18716,55.7,5.4,16.6,13.8,0.5,92.1,7.9,"$11,264"
30,2019,New Mexico,158.2,4245,36.6,4.0,32.7,15.0,1.8,90.2,9.8,"$8,459"
31,2019,New York,166.6,43806,49.8,5.8,25.7,13.0,0.4,94.7,5.3,"$12,932"
32,2019,North Carolina,154.7,19617,46.3,6.7,17.9,15.3,2.4,88.6,11.4,"$8,619"
33,2019,North Dakota,147.7,1448,55.7,9.0,12.2,13.8,2.1,92.6,7.4,"$10,653"
34,2019,Ohio,188.8,29160,52.6,4.0,20.0,15.9,0.8,93.3,6.7,"$10,173"
35,2019,Oklahoma,231.4,10960,45.5,5.5,17.0,15.1,2.0,85.1,14.9,"$8,923"
36,2019,Oregon,131.0,7128,49.3,5.7,20.8,16.2,0.9,92.9,7.1,"$9,635"
37,2019,Pennsylvania,172.9,32299,51.8,5.1,20.2,16.3,0.8,94.3,5.7,"$11,175"
38,2019,Rhode Island,159.3,2404,54.0,5.9,20.5,14.6,0.8,95.7,4.3,"$10,988"
39,2019,South Carolina,164.0,10579,45.4,6.1,18.8,16.8,2.2,89.2,10.8,"$8,345"
40,2019,South Dakota,158.1,1840,51.5,8.3,12.8,16.1,1.8,90.4,9.6,"$11,627"
41,2019,Tennessee,202.8,16814,47.8,5.6,19.5,15.0,1.8,89.8,10.2,"$8,827"
42,2019,Texas,163.4,46139,47.6,5.7,15.9,10.9,1.6,81.6,18.4,"$8,028"
43,2019,Utah,146.5,3882,60.5,9.3,9.3,10.0,1.2,90.4,9.6,"$7,193"
44,2019,Vermont,151.6,1368,48.4,4.8,23.9,17.5,1.0,95.6,4.4,"$12,159"
45,2019,Virginia,149.1,15062,54.1,5.2,13.5,14.8,4.4,92.0,8.0,"$8,826"
46,2019,Washington,134.8,11862,52.9,5.0,19.8,13.9,1.8,93.4,6.6,"$8,964"
47,2019,West Virginia,197.4,5087,44.0,2.5,26.6,19.0,1.3,93.4,6.6,"$11,951"
48,2019,Wisconsin,158.8,12241,56.5,5.3,16.1,15.5,0.8,94.2,5.8,"$9,652"
49,2019,Wyoming,150.4,1067,51.1,7.1,11.5,16.2,1.8,87.7,12.3,"$10,111"